"""empty message

Revision ID: 1db83e2923ed
Revises: 
Create Date: 2022-09-02 22:30:21.116664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db83e2923ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Case_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Case_status', sa.String(length=50), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('lawyer_identification', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('first_lastname', sa.String(length=120), nullable=False),
    sa.Column('second_lastname', sa.String(length=120), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=500), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('exp_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('init_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Email_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Case_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['Cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('Case_updates_id', sa.Integer(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['Case_updates_id'], ['Case_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Files')
    op.drop_table('Case_updates')
    op.drop_table('Phone_number')
    op.drop_table('Email_address')
    op.drop_table('Cases')
    op.drop_table('Address')
    op.drop_table('notifications')
    op.drop_table('Notes')
    op.drop_table('Clients')
    op.drop_table('Users')
    op.drop_table('Case_status')
    # ### end Alembic commands ###
