"""empty message

Revision ID: 9df733af7199
Revises: 207d65b783d8
Create Date: 2022-08-09 03:19:04.656092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df733af7199'
down_revision = '207d65b783d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_first_lastname_key', 'clients', type_='unique')
    op.drop_constraint('clients_name_key', 'clients', type_='unique')
    op.drop_constraint('clients_second_lastname_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_second_lastname_key', 'clients', ['second_lastname'])
    op.create_unique_constraint('clients_name_key', 'clients', ['name'])
    op.create_unique_constraint('clients_first_lastname_key', 'clients', ['first_lastname'])
    # ### end Alembic commands ###
