"""empty message

Revision ID: b65a6fbdbbbd
Revises: 0028c04936a0
Create Date: 2022-08-09 02:01:04.893224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65a6fbdbbbd'
down_revision = '0028c04936a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'clients', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
