"""empty message

Revision ID: f6adcafe3819
Revises: b65a6fbdbbbd
Create Date: 2022-08-09 02:05:03.722449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6adcafe3819'
down_revision = 'b65a6fbdbbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
